### ISSUE TITLE
Game Pass Domestic mode incorrectly limits access to the NFL Network section

### ISSUE THREAD

**Issue by HenioH** [aqw/xbmc-gamepass#267]
The NFL Network tab now does not work it doesn't display any info that has been there for the last year..
Noticed it does not let me choose domestic or international in settings as well anymore?

Update: realized with your update you added the auto detect sub which killed the cool function for us Domestic users being able to just select International and allowing us the benefits of the NFL Network tab that international users had. If that was intended no problem.

**Comment by Alexqw** [comment]
@HenioH did you update from version 0.9.1 or something a bit earlier? The code for acquiring the NFL Network shows was significantly changed between 0.9.0 and 0.9.1, but was left unchanged in 0.9.2. In any case, please restart Kodi, enable debugging in both Kodi and the addon, and provide the log here.

As for the removal of the domestic vs international setting, that's because there's no need any longer; it's auto-detected now. From how we understand how Game Pass's auth works, a domestic account cannot successfully authenticate to the international servers (nor vice versa). The Game Pass server response provides info as to whether they detect you're 'domestic' or not, so we just rolled the setting into an auto-detect feature for that response.

---Alex

**Comment by HenioH** [comment]
The prior 0.9.1 and previous versions allowed domestic users to go into settings and select international which allowed us to use the live NFL Network features which otherwise would be blocked for domestic users. As of now with the auto detect it kills the benefit for the Domestic users to select International manually and use the benefits under the NFL Network tab. So that feature glitch is no longer since we cant manually select between domestic and international :( I will staying on the 0.9.1 as it allows those benefits still.

**Comment by aqw** [comment]
@HenioH Where are you located geographically? And which features could you previously access that you no longer can?

What you're telling me surprises me, as we have many logs from users in the US that tells a different story.

---Alex

**Comment by HenioH** [comment]
I live in California USA. I understand as a domestic user I was not allowed to watch the games live under the Gamepass Tab. That will always be the case having a domestic subscription. In the prior versions from 0.9.1 and under we had the option to select Domestic or International in the settings. When Domestic was choosen the NFL Network Tab features did not function like the Live NFL Network, Redzone Archives, Hard Knocks, Game Day, Etc...But when you manually select International in the settings it allowed those features to function even if you had a Domestic account under the NFL Network tab...of course this is all without any proxy setup. With the auto detect it automatically selects Domestic which then kills the NFL Network tab features. Couldve been a glitch that allowed Domestic user to access thoughs features but was a huge benefit of being to select International while still having a Domestic Subscription.

**Comment by aqw** [comment]
@HenioH Ahh, I understand now.

So, just to be clear, you could not ever watch "live" games yes? But the problem now is that quite a few things in the UI are hidden, such as NFL Network, the shows, etc.

This might be a leftover from the old NFL Game Rewind days (the precursor to Game Pass Domestic) when the service didn't offer those features and so hid them in UI. I'll take a look at the code, perhaps it's as simple as unhiding them.

---Alex

**Comment by aqw** [comment]
@HenioH I can't test this, as I'm not in the US, but try changing line 442 in default.py from:

    if gpr.subscription == 'international':

to

    if True

You'll need to exit the addon and re-enter it after the change is made. Let me know how that works out for you.

---Alex

**Comment by HenioH** [comment]
Yes exactly.. That would greatly appreciated as those extra options from having such a restricted Domestic Subscriptions was a huge benefit. I uploaded a quick video so you can see me changing between International and domestic and how the NFL Network tab reacts. Excuse the sloppy camera work hard to hold phone and use the Nvidia Shield game controller

https://www.youtube.com/watch?v=fn42SAm5AMQ

**Comment by HenioH** [comment]
ok let me edit the .py and let you know.

**Comment by aqw** [comment]
@HenioH Excellent. I'll likely get around to committing this fix on Monday.

Thanks for taking the time to report this bug. Game Pass Domestic users are rare around here, so your feedback is quite valuable.

---Alex

**Comment by HenioH** [comment]
No problem glad to help in anyway possible.

**Comment by sportshd** [comment]
Is it possible to have the option of turning off auto detection and have the option of manually selecting domestic or international. Thanks

**Comment by sportshd** [comment]
I made the change my line 442 looks like this
if True == 'international':

I am still getting nothing when I click on NFL Network.

**Comment by HenioH** [comment]
it should be

if True

that's it nothing else in that line just those two words

**Comment by sportshd** [comment]
I made the change saved it and started kodi again and now the addon doesn't launch any more.

I am on windows 10 jarvis 16.1

**Comment by aqw** [comment]
@sportshd You likely edited it incorrectly. Either wait until Monday when I make the change and commit it, or double check that file and make sure it is exactly as stated above. Specifically, make sure the indentation matches what the original had (indentation is meaningful in Python).

---Alex

**Comment by sportshd** [comment]
Ok thanks, I think it would be nice to be able to disable the auto detect feature and let us choose between domestic and international. I think the domestic users would agree.

**Comment by aqw** [comment]
@sportshd I am open to bringing back the setting to choose which subscription type /if/ indeed it turns out it would actually do something. ;-)

As of now, I'm unconvinced and I believe the code is working as intended. I've pushed the change that fixed the original problem in this issue. We'll wait a few days, and see if that resolves people's perceived problems.

---Alex
