### ISSUE TITLE
Show Game Info (time, etc) even when game is blacked out

### ISSUE THREAD

**Issue by HenioH** [aqw/xbmc-gamepass#269]
Last Season they showed the schedule but if you attempted to play a game under a domestic sub it would just give you the bad juju error which was expected. So far for this season under Domestic all regular season games say Blacked Out on schedule for every week. Is this how it will be for the entire year? Without the schedule?

**Comment by kaileu** [comment]
Are we talking from Live Games or archived ones?

Mit freundlichen Grüßen
Kai Leutner

**Comment by HenioH** [comment]
Live Games. All Games now show Blacked out which on domestic you cant watch live but the schedule was always available before.

**Comment by kaileu** [comment]
Yes we marked this Games as BlackedOut because otherwhise people are  
confused because of Games which are listed but not Playable because of  
region restrictions. If other people need still the Schedule maybe  
this can integrated in the ui.

Mit freundlichen Grüßen
Kai Leutner

**Comment by HenioH** [comment]
Having the schedule was a big benefit as it allowed us in the USA to know when each game started according to our favorite teams. Also let us look for live links on other live options that had no schedule information.

**Comment by HenioH** [comment]
Quick Question.. If I sign up for the NFL GamePass through a VPN as international and then setup a proxy in the GP addon will that allow me live game service?

**Comment by kaileu** [comment]
As itbis against the TOS of NFL Gamepass we can't support those  
questions/setups.

Mit freundlichen Grüßen
Kai Leutner

**Comment by HenioH** [comment]
No problem I understand. 

Would you be able to answer if the Proxy Settings in the GP addon function correctly? or just an old setting feature that no longer functions?

**Comment by kaileu** [comment]
Yes the ProxySetting is still working.

Mit freundlichen Grüßen
Kai Leutner

**Comment by HenioH** [comment]
Thank you so much for being so helpful. Really appreciate it. 

Take care

**Comment by aqw** [comment]
I'm not sure if there is room in the UI for this information, but I updated the Issue Name and maybe someone will take a whack at it. :-)

Another option is to find some way, other than text, to convey clearly that the game is blacked out. 

---Alex

**Comment by HenioH** [comment]
Thank you having an available schedule is always helpful. Maybe if possible for upcoming can say Blacked out while still keeping the time and date of game.

**Comment by HenioH** [comment]
I am now getting the logging into NFL Game Pass failed error. I have checked my ingo and its correct as well as being able to sign into it from the NFL webpage.

**Comment by kaileu** [comment]
I guess you have Problem with the Proxy settings ;-)
On Most Cases you have to restart Kodi aber setting the Proxy.

Mit freundlichen Grüßen
Kai Leutner

**Comment by HenioH** [comment]
Not using a proxy at the moment. Did restarts and cleared cache to be safe. But still gettting logging into NFL issue. Reinstalled the 0.9.1 and it works. Just started with the error today. Could it be the edit done by Alex earlier about the domestic games showing Blacked Out. I am a Domestic User in California.

**Comment by kaileu** [comment]
Could you enable the debugging in Kodi and in the Addon try to loggin  
in and post a log?

Mit freundlichen Grüßen
Kai Leutner

**Comment by HenioH** [comment]
It actually let me log in once I reinstalled the 0.9.2 again. Guess it was just a hiccup. Working back as it was..Thanks for the speedy replays

**Comment by castlenova44** [comment]
Hey guys I'm having the same issue with it saying the log in error I Uninstalled it didn't working updated it didn't work. Then I tried the debugging but nothing any suggestions please

**Comment by kaileu** [comment]
I didn't get it what exactly is your problem?
And please upload a debug log

Mit freundlichen Grüßen
Kai Leutner

**Comment by castlenova44** [comment]
It won't work it says there is an issue logging in. 
How do I upload the debug log?

**Comment by HenioH** [comment]
Same thing it came back as of this morning was using it fine the all of a sudden cant log in error. WHen I uninstall 0.9.2 then reinstall 0.9.1 it works

**Comment by castlenova44** [comment]
Yea I tried it too but it didn't work

**Comment by HenioH** [comment]
Its weird on my Shield it wont log in but on my firestick and fire tv box it works fine and im using the same zip file

**Comment by aqw** [comment]
@HenioH It's likely something with your network setup. Also, you've been around here for long enough to know that it is basically impossible for anyone to help you with troubleshooting without a log file. If you're reporting problems without providing a debug log, it's basically just noise.

---Alex

**Comment by HenioH** [comment]
The login error is happening again when prior it was working perfectly. My network has never had any problems using the GP until a couple days ago. I also tried at another location and same log in error. my username and password are correctly typed in as I can sign into the gamepass from the NFL website.
I deleted my login credentials from this log

[NFL GP LOG.txt](https://github.com/aqw/xbmc-gamepass/files/466775/NFL.GP.LOG.txt)

**Comment by kaileu** [comment]
Its your Proxy that causes the issue so we can't help you :-(
Line 863 to 869 of your Logfile.

**Comment by aqw** [comment]
@HenioH In the response from the GamePass servers, it doesn't provide the subscription info for you. As for 0.9.1 works but not 0.9.2, I have no idea, as the subscription detection code has not changed in a long time.

Also, I should have mentioned this before, please don't hijack issues which are unrelated to your problem. Open a new issue.

@kaileu Those /might/ also be due to him using a super old version of Python (2.6.5). But yes, old python with proxy -> fail.

---Alex

**Comment by aqw** [comment]
Closing. If this is still a problem, please reopen and provide a debug log.

---Alex

**Comment by castlenova44** [comment]
I have nothing to do with this why am I on this email thread

**Comment by aqw** [comment]
@castlenova44 Your GitHub settings probably have you autosubscribe to issues you've commented in (which you did, three times). Unsubscribe from this issue and/or change your settings, and you won't receive any more emails.

---Alex

**Comment by castlenova44** [comment]
Thanks
