### ISSUE TITLE
Game Pass on Krypton

### ISSUE THREAD

**Issue by Doug-Shannon** [aqw/xbmc-gamepass#270]
Hey Guys,  I had to install Krypton to get gamepass working on my nvidia shield (issue with an older version of python).  When I upgraded to Krypton, gamepass was working.  Gamepass then stopped working and I did not correctly Identify that it was the actual gamepass service that had gone down and decided to try and reinstall gamepass to get it working again.  unfortunately I cannot find the gamepass package on the krypton repositories now and have no clue how to reinstall it.  I'm on an android NVidia shield box and have limited ssh access.  What should I do?

**Comment by aqw** [comment]
@Doug-Shannon Active effort to support Krypton will begin soon (see #234). Currently, to install this addon on krypton, you need to edit the ``<import addon="xbmc.gui" version="5.10.0"/>`` line to read ``5.12.0``.

---Alex

**Comment by kaileu** [comment]
@aqw why did we have this line?
I removed it and it didn't changed anything maybe we can get rid of it?


Mit freundlichen Grüßen
Kai Leutner

**Comment by aqw** [comment]
@kaileu I believe it's required (or at least was required at one time). @eriksoderblom or @BaumSchorle might have more info.

There tends to be breaking changes across Kodi releases, so Kodi checks for those values and enforces them.

When you removed the line, did you restart Kodi as well (to kill any caching)? IIRC, we needed that line for Kodi to even expose the skinning APIs to the addon.

---Alex

**Comment by kaileu** [comment]
Yes i restarted Kodi and it still works.

Mit freundlichen Grüßen
Kai Leutner

**Comment by Displayel** [comment]
Krypton Beta 2 is out, when i installed it and started it, right after the start a popup came up and it said something like "detected one not compatible addon gamepass" it gets automatically deactivated then, but if you activate it again and run it everything works fine for me.

**Comment by Ghoschdi** [comment]
@Displayel: Tried to reproduce this and did not encounter this neither on Windows nor on Shield TV.

By the way i can second @kaileu statement re removing the `<import addon="xbmc.gui" version="5.12.0"/> `. Tried this on both my machines with the  recent Kodi 17B2 including remove, installing etc. Works without that line.

**Comment by Displayel** [comment]
@Ghoschdi well its Krypton B4 by now and the addon will still get deactivated right at the start on my shield

**Comment by Ghoschdi** [comment]
@Displayel: Just came back from business travels and will test this tonight.

**Comment by Ghoschdi** [comment]
@Displayel: Sorry for taking longer. Tested it, same as before, no issues. Works out of the box. Strange...

**Comment by DOGGYBONE** [comment]
I'm having the same issue GamePass addon not compatible with Krypton, but I have read you can change the line code, so if someone can copy and paste this code and explain where to add it. Thanks!!

**Comment by aqw** [comment]
Closing, see #234
