### ISSUE TITLE
Logging in error

### ISSUE THREAD

**Issue by HenioH** [aqw/xbmc-gamepass#271]
Sorry about that didn't mean to hijack that thread. 
I have set the GP addon to default with no proxy settings if that's what you meant by a proxy. 

[UPDATED NFL GP LOG .txt](https://github.com/aqw/xbmc-gamepass/files/466850/UPDATED.NFL.GP.LOG.txt)

**Comment by kaileu** [comment]
You said "I am a Domestic User in California."
So youre log says your trying to Login to Gamepass International from Germany.
So you must using a proxy/vpn/dns resolver/etc.
The Service you are using can't handle the ssl login site and throws the error i pointed to.

**Comment by kaileu** [comment]
Did you check the Proxy Settings of kodi itself ?
Under Options/Settings/System/Internet Connection ?

**Comment by aqw** [comment]
@HenioH Just to make sure I understand this correctly:

* you're a domestic user in CA
* 0.9.1 on your Shield works
* 0.9.2 on your shield doesn't work
* 0.9.1 and 0.9.2 on your Fire Stick and some other device works
* you're not using any form of proxy, VPN, etc.
* and despite this, Game Pass's servers think you're located in Germany

Can you provide the debug log for either 0.9.1 on the Shield and/or 0.9.2 on the Fire Stick? That way we can compare.

---Alex

**Comment by HenioH** [comment]
I think I figured it out. I did attempt a proxy yesterday but then cleared it from the addon on settings. I believe the add_data kept a record of it in the settings so I deleted that plugin.video.nfl.gamepass folder and restarted the GP addon and it works now.

**Comment by aqw** [comment]
Closing.
