### ISSUE TITLE
trouble logging in

### ISSUE THREAD

**Issue by brajohns42** [aqw/xbmc-gamepass#272]
I am running GP 0.9.2 on Jarvis 16.1. I had the GP login working yesterday with no issues but today it is giving me login errors. I can log in to the GP website on my laptop and watch everything, so I know I have an account and my login is working. I have checked and re-checked the login information in the GP add-on configuration. The log is here (same log errors every time):

22:06:17 T:1406219088 WARNING: static XFILE::IFile* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(script) in script://plugin.video.nfl.gamepass/-poster.jpg
22:06:17 T:1406219088 WARNING: static XFILE::IFile* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(script) in script://plugin.video.nfl.gamepass/-poster.png
22:06:17 T:1406219088 WARNING: static XFILE::IFile* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(script) in script://plugin.video.nfl.gamepass/-banner.jpg
22:06:17 T:1406219088 WARNING: static XFILE::IFile* XFILE::CFileFactory::CreateLoader(const CURL&) - unsupported protocol(script) in script://plugin.video.nfl.gamepass/-banner.png
22:06:18 T:1417727336  NOTICE: [plugin.video.nfl.gamepass-0.9.2]: script starting
22:06:19 T:1417727336   ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:315: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#snimissingwarning.
                                              SNIMissingWarning
22:06:19 T:1417727336   ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/util/ssl_.py:120: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
                                              InsecurePlatformWarning
22:06:19 T:1417727336   ERROR: /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/script.module.requests/lib/requests/packages/urllib3/connection.py:266: SubjectAltNameWarning: Certificate for gamepass.nfl.com has no `subjectAltName`, falling back to check for a `commonName` for now. This feature is being removed by major browsers and deprecated by RFC 2818. (See https://github.com/shazow/urllib3/issues/497 for details.)
                                              SubjectAltNameWarning
22:06:20 T:1417727336  NOTICE: [plugin.video.nfl.gamepass-0.9.2]: login failed

**Comment by aqw** [comment]
@brajohns42 It's hard to tell without a more complete debug log (the addon's debugging also needs to be enabled), but I'm going to guess it's the well-known SSL redirect problem #183.

If so, there's nothing we can do about it. Either stop using a proxy and/or upgrade your version of Kodi and/or upgrade your OS/platform to get a newer version of Python.

---Alex

**Comment by brajohns42** [comment]
Thanks Alex. I had debugging enabled for the GP add-on, unless there's a setting somewhere I missed. 

I'm running on Amazon Fire stick so there's little I can do about a platform upgrade except wait. 

What version of Kodi should I upgrade to? And why would it work literally the day before but not now?

**Comment by brajohns42** [comment]
Welp, it started working again. I just tried it tonight and haven't changed a thing.

**Comment by aqw** [comment]
@brajohns42 Glad to hear it's working. Don't know why you experienced an intermittent problem, but it's most likely SSL/Proxy related.

Closing.

---Alex
