### ISSUE TITLE
Log-in error

### ISSUE THREAD

**Issue by az-chris** [aqw/xbmc-gamepass#275]
Hi, for some reason I am having problems logging into the add-on.  Via the web I can log in, no problems.  I have used the built in kodi keyboard and the android tv app keyboard. Tried swapping username/e-mail. No luck.  Just the "Logging into NFL Game Pass failed. Make sure that your account information is correct and your subscription valid." Installed via the kodi official add-on market.

**Comment by kaileu** [comment]
Without a log file we can't say whats wrong.
We need a log file with enabled debug in Kodi and Addon

Mit freundlichen Grüßen
Kai Leutner

**Comment by Sebi0902** [comment]
Hallo Kai,
Ich habe dasselbe Problem. 
Habe mich gerade erst hier angemeldet, wie kann ich dir die logfile zukommen lassen? 
 LG

**Comment by kaileu** [comment]
Hi Sebi,

hier ist es beschrieben wie man das macht :)
http://kodi.wiki/view/Log_file

Liebe Grüße

**Comment by aqw** [comment]
Closing as there's been no information or log provided. @Sebi0902 please reopen if you're still having the problem and provide a log.

---Alex
