### ISSUE TITLE
Audio passthrough for Android TV version

### ISSUE THREAD

**Issue by juscelinofs** [aqw/xbmc-gamepass#281]
First of all, thanks for your brilliant job on the new version.
Are there any news on audio passthrough issues for Android TV (Sony Bravia)?
Thanks all for the hard work.

**Comment by kaileu** [comment]
This Problem is not addon related.
You have to contact the Kodi developer or the spmc maintainer

Mit freundlichen Grüßen
Kai Leutner

**Comment by aqw** [comment]
@juscelinofs I'm glad you appreciate the addon. @kaileu is right though that what you describe is an issue with Kodi and not with this addon.

---Alex
