### ISSUE TITLE
Live Stream problem on Wetek Play 2

### ISSUE THREAD

**Issue by Donl5355** [aqw/xbmc-gamepass#284]
On my Wetek Play 2 the live stream  only works when i disable the hardware acceleration. I have the latest libreelec v7.90.010 ALPHA.

**Comment by aqw** [comment]
@Donl5355 This is a hardware and/or ELEC issue, and has nothing to do with our addon.

As a plus, it sounds like you've solved your problem. ;-)

---Alex
