### ISSUE TITLE
Games do not start (black screen)

### ISSUE THREAD

**Issue by totti50189** [aqw/xbmc-gamepass#288]
Hi,

I have a problem with running the NFL Gamepass international. I have a full subscribed international Gamepass and I am sitting in Germany so no legal aspects should be relevant.

I am running Kodi/XBMC 16.1 RC2 on a Vu Solo2 and have installed the Gamepass Version 0.92.

When I start a game (doesn't matter which) the screen just becomes black and nothing happens (also no sound). I can easily leave the game, so the system is not crashed and no log file is created.

I installed Kodi on my pc to test it and it worked fine so I don't have any idea what to do. I changed already the stream quality but didn't change anything :(

Could you help me?
Thank you

**Comment by aqw** [comment]
Hey @totti50189 

Thanks for the bug report. I just tested my setup, and everything is working for me. I'm also in Germany with a full subscription.

Two questions:

* any reason why you aren't running Kodi 17?
* is there really no log file? Kodi creates one automatically. You should enable debugging in both Kodi and the addon, find the log file, and submit it. [1]

Once we have the log file, we have a better chance of figuring out what's going on.

---Alex

[1] http://kodi.wiki/view/Log_file

**Comment by totti50189** [comment]
Hi Alex,

thank you for the quick answer. I am running Kodi 16 as this is the
"standard" Version for the VU+ Set-Up Box with VTI Image. Regarding the
look file: I checked in the folder for kodi logfiles for linux/enigma
systems but there is no file :(

Does the Game Pass not run with Kodi16.2?

Thanks for your support
Thorsten

2017-05-24 11:39 GMT+02:00 Alex Waite <notifications@github.com>:

**Comment by aqw** [comment]
>  Regarding the look file: I checked in the folder for kodi logfiles for linux/enigma systems but there is no file

I've never used the enigma/VU+ systems, but I'd be amazed if there's no log file. And if there isn't, then.... well, that's just a very, /very/ foolish decision on their part.

Without the log file, I can't be of much help.

>  Does the Game Pass not run with Kodi16.2?

It does run on Kodi 16.x. However, all future development will be on Kodi 17. And, please keep in mind, every August, GamePass changes "stuff" and the addon breaks for a few weeks while we scramble to figure out what's changed and how to fix it. The point being, it's best to be on the most recent stable release of Kodi, which is 17.

But, I don't know if that'd fix your problem, as without the log file, it's impossible to tell what's going on. If I had to take a wild guess, I'd suspect something in your Kodi's hardware acceleration settings, but the lack of sound is a bit odd, so it's hard to say.

---Alex

**Comment by totti50189** [comment]
Hi,

thank you for the answer and very good hint regarding the update in August.
So I will search for another Image that supports Kodi17 and hope that it
will work.

Thank you.

Cheers
Thorsten

2017-05-28 22:29 GMT+02:00 Alex Waite <notifications@github.com>:

**Comment by aqw** [comment]
@totti50189 Best of luck. :-)

---Alex

**Comment by totti50189** [comment]
Hi, 

I just installed Open Black Hole which supports Kodi 17.3. I deinstalled the NFL Game Pass App and re-installed it. Now, when I start a Game, Kodi shows very shortly the "Player interface" and the file name but afterwards, instead of playing the game it brings me back to the Game Pass Game Selection Screen.

The good thing is: This time I have a Logfile :)

Could you please have a look and thank you againg for your support


[kodi_log.txt](https://github.com/aqw/xbmc-gamepass/files/1036540/kodi_log.txt)

**Comment by kaileu** [comment]
Nutzt du einen Proxy?
Das Problem ist dass deine Verbindubg beim runterladen des Manifests austimed wenn ich das richtig sehe.

**Comment by totti50189** [comment]
Nein, alles ganz legal. Deutscher GamePass, deutsche Location.

2017-05-29 21:56 GMT+02:00 kaileu <notifications@github.com>:

**Comment by kaileu** [comment]
@aqw did you have an idea what could cause this problem?

19:31:55.368 T:1961909568   ERROR: CCurlFile::Stat - Failed: Timeout was reached(28) for 


@totti50189
Tritt das Problem nur bei den 3k bitraten auf oder auch bei niedrigeren?

**Comment by totti50189** [comment]
@kaileu Bei allen verschieden, habe es von 4500 - 300 k/bits mit fast allem versucht.

**Comment by aqw** [comment]
@kaileu Hmm, you're right. It does seem to be a timeout problem. No idea why he's running into that though. My best guess, which isn't great, is that the Kodi build he's using is applying some non-standard patches and isn't passing the cookies and/or the http headers along to ffmpeg. Really hard to say though.

@totti50189 Are you able to play games on this machine using the web interface?

---Alex

**Comment by totti50189** [comment]
@aqw Hi Alex, no the console doesn't even start. But the browser seems to be very limited.

**Comment by aqw** [comment]
@totti50189 Is this still a problem with you with the new Game Pass service?

---Alex

**Comment by totti50189** [comment]
Hello Alex,

thank you for asking. Unfortunalety yes. I reset the box completly and installed kodi again but it still didn’t work while it was easily working on my Laptop. So I just decided to stop trying it and hope that there will be a new Version of the Image with the current Kodi and until then I watch via HDMI from my PC.

But did you allready manage to update the kodi game pass app to the new game pass Player? Because this „update“ from NFL Networks is really bad and misses a lot of functionalities. Really looking Forward to use KODI and your App instead.

Cheers
Thorsten





Gesendet von Mail für Windows 10

Von: Alex Waite
Gesendet: Montag, 14. August 2017 13:37
An: aqw/xbmc-gamepass
Cc: totti50189; Mention
Betreff: Re: [aqw/xbmc-gamepass] Games do not start (black screen) (#288)

@totti50189 Is this still a problem with you with the new Game Pass service?
---Alex

**Comment by kaileu** [comment]
Hi Thorsten,

most of the functionalities is working.
Most of the new Changes (on Github) are cosmetic ones for cleaner Code.
But if you are inside Europe you should be fine using the Addon for most of the new Content:)
The Support of the old content is removed (from nfl side) and some are not tested because they are not available at the moment like RedZone.

Mit freundlichen Grüßen
Kai Leutner

**Comment by aqw** [comment]
@totti50189 Thanks for the update. We have indeed updated the addon to use the new service, and it should be stable(ish).

If you re-encounter this problem (and the web interface works perfectly on the same computer), then feel free to reopen this issue.

Enjoy the season!

---Alex
