### ISSUE TITLE
Previous Years.

### ISSUE THREAD

**Issue by HenioH** [aqw/xbmc-gamepass#300]
Hello 

Noticed with the newest update in the GamePass section we can no longer access any year prior to 2016? I was able to access all the way to 2011 before the 2017 year was added. Will this be added later? 

Also is version 0.11.0 available? I only see 0.10.2 

Thanks

**Comment by kaileu** [comment]
The Problem with the newest update is that NFL Gamepass for Europe has a diffrent Provider as before. The new Provider only supports the new content from 2017 onwards.

**Comment by HenioH** [comment]
Ahhhh... ok got it. Thank you for the clarification.

**Comment by aqw** [comment]
@HenioH There is no 0.11.0 release yet, but all the code is in the master branch on GitHub. So you can use that. I plan to release 0.11.0 about halfway into the pre-season. I don't want to spam the Kodi devs with updates to the addon (they don't like that), so I figure ~2 weeks of the developers cleaning stuff up and bleeding-edge users testing, followed by 2 weeks of actual release into the Kodi repo. That should give us enough time and coverage to make sure things are working for the regular season.

---Alex
