### ISSUE TITLE
From US willing to help if I can

### ISSUE THREAD

**Issue by anotherthief** [aqw/xbmc-gamepass#302]
Not good at coding so unfortunately I can't be much help in that area. But I am, however, willing to sign-up for the 7 day trial for the US version and use wireshark (or whatever else) to retrieve any info that you may need if that would help at all. Just guide me in the right direction on what to use, what to do and how to do it. 

That would atleast give you guys(or us) 7 days to get whatever info you need. Unfortunately, I don't wanna buy a year sub because I use the international version so that I can watch the games live. 

I know that this isn't exactly ideal, but it's only a suggestion is all. If this won't help or if you don't think this is necessary then please disregard this post. 

Let me know. I'll check back later. I'm on EST timezone(9pm right now) so bare with me.

And sorry for posting this as an "Issue" too.

**Comment by aqw** [comment]
@anotherthief Thanks for the offer. We could do something like that ourselves as well, but we really need someone who can help keep things working as the season progresses (longer than just 7 days).

---Alex
