### ISSUE TITLE
NFL Network Live - Unsupported format

### ISSUE THREAD

**Issue by jake404** [aqw/xbmc-gamepass#303]
I have the Git Master version installed and logging in works fine and playing from the GamePass tab works but when trying to play the live stream under the NFL Network tab, it shows a spinner and then nothing happens. The log says unsupported format:

```
14:09:17.641 T:418840  NOTICE: VideoPlayer: Opening: https://livemain-i-video-nfl.akamaized.net/ch21/1b3efacc-0628-4c37-8318-c555535e8e19/d4ad7c6c-262d-4c9f-a9eb-3fed083a492d.ism/QualityLevels(4749952)/Manifest(video,format=m3u8-aapl-v3,audiotrack=audio,filter=hls)?hdnea=st=1502194157~exp=1502194182~acl=/*~hmac=6d671a87b68ee8298637eec8e1d9389a81aef1125f40a5573f0754eba8fef857&hdcore=2.11.3|Connection=keep-alive&User-Agent=Safari%2F537.36+Mozilla%2F5.0+AppleWebKit%2F537.36+Chrome%2F31.0.1650.57
14:09:17.641 T:418840 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
14:09:17.655 T:418840   ERROR: DXVA::CProcessorHD::IsFormatSupported: Unsupported format 105 for 1.
14:09:17.655 T:421428  NOTICE: Creating InputStream
14:09:17.739 T:421428  NOTICE: Creating Demuxer
```

I have the setting 'preferred stream quality' set to 'always use highest bitrate'.
Anyone else that had the same issue?

**Comment by Ghoschdi** [comment]
Just gave it a try, works flawless here in Germany with latest master and active Kodi on windows platform. Have a chance to test NVidia Shield TV based Kodi later.

**Comment by kaileu** [comment]
@jake please upload a full debug log

**Comment by jake404** [comment]
I noticed that it does work if I keep trying over and over... that results into about 5%-10% of the times.
Could it be that it tries to access different streaming servers each time?

Here is the log file: [kodi.zip](https://github.com/aqw/xbmc-gamepass/files/1208975/kodi.zip)

**Comment by Displayel** [comment]
Works fine on Nvidia Shield in Germany

**Comment by RedManMark86** [comment]
Hi,

I am in the UK and getting exactly the same error. I have tried running through a VPN using both Germany and France and that doesn't work either. I can watch on the site fine but obviously that means nothing. Any stream I try gives the same error as above?

**Comment by kaileu** [comment]
Something i noticed if i ran Kodi in a virtual maschine its the same error.
If i am on bare Metall Hardware its fine.
(Same Maschine) so i think its a Kodi Problem.

**Comment by jake404** [comment]
I have tested on two different Windows machines, one that I use everyday and another that was a clean install. Both have the same issue. Like I mentioned, I can watch everything except the live stream 100% of the times and the live stream only works a few times out of a hundred. If it's a Kodi issue then nothing should work. I didn't have any issues last season.

**Comment by kaileu** [comment]
You can't compare with last year.
The new streams has a diffrent encoding as far as i noticed.
Try to install the nightly build and test it there.

**Comment by RedManMark86** [comment]
I actually did manage to get mine working... In the addon preferences I had set my stream quality preferences. I set this to always ask and now it works 8 times out 10, rather than never, so it works most times now.

**Comment by jake404** [comment]
I installed the latest nightly but it didn't help. I guess I just have to use Chrome instead. Bummer!

**Comment by RedManMark86** [comment]
Did you try what I said by setting the stream quality to ask?

**Comment by jake404** [comment]
Yeah, it didn't help. When the dialog comes up I tried all the available qualities.

**Comment by JKne** [comment]
Same problem here. Also from Germany. 

I have a media pc with a nvidia ion gpu and an intel atom in it. 

Kr

**Comment by RedManMark86** [comment]
I know this isn't particularly helpful but there is a subreddit for NFLStreams and they use the same system here to play the streams at their max quality in 720p striaght of the NFL servers. I have no idea exactly how it works but I'm trying to work it out so I can get them on VLC for now as the Kodi plugin right now half works, it for some reasons tend to pause and buffer a lot on any live stream when I tested yesterday but not on replays.

**Comment by kaileu** [comment]
@RedManMark86 its illegal.
So don't post such Methods/Ideas.

**Comment by RedManMark86** [comment]
@kaileu , sorry didn't mean to push something illegal as I use a paid subscription, was just trying to offer an alternative whilst you work on adapting to the new system so it is more stable and mine does work, just with lots of buffering/pausing when it does connect the 8 out of 10 times.

**Comment by kaileu** [comment]
The Links are illegal even if you have a valid subscription.
These Problems are more related to Kodi not the addon itself.

**Comment by RedManMark86** [comment]
I'll be honest I still prefer Kodi 16 but the addon only works with 17 so I had to make the move. I didn't give a direct link though just in case it was against the rules. Sorry again.

**Comment by kaileu** [comment]
I did a deeper look and on my vm machine and there Kodi has a problem with the audio Stream of the Live Games.

**Comment by kaileu** [comment]
Maybe the Chromecast Streams is better for Kodi on some Platforms.
Please test the new Master Version.

**Comment by jake404** [comment]
So far it's working great and it's 1080. Awesome!

**Comment by RedManMark86** [comment]
That made a massive improvement, all work every time on first selection!

**Comment by aqw** [comment]
I'm goign to close this as it sounds like @kaileu's patch is helping a lot here. :-)

---Alex
