### ISSUE TITLE
Login erorr

### ISSUE THREAD

**Issue by Yaya7** [aqw/xbmc-gamepass#304]
Hi  I have prob with that new version i cant  log in im in europe  but still  have prob can fix  this to watch tomorrow's games ?

thanks

**Comment by kaileu** [comment]
You have to post a full log with debug mode enabled.

Mit freundlichen Grüßen
Kai Leutner

**Comment by Displayel** [comment]
did you update to the latest version provided here on github ? got the login error too after the update it worked again.

**Comment by CraigMack69** [comment]
all fine for me watching panthers game

**Comment by pchestek** [comment]
I have the same problem, https://paste.ubuntu.com/25280639/

**Comment by kaileu** [comment]
@pchestek you have to use the git version master. The one out of the repo ist not working at the moment.

**Comment by pchestek** [comment]
Ah, ok, thanks. A new adventure!

**Comment by pchestek** [comment]
Got it working, thanks so much!

**Comment by aqw** [comment]
@Yaya7 Have you tested with latest git's master?

---Alex

**Comment by Yaya7** [comment]
yep its works thanks

**Comment by aqw** [comment]
@Yaya7 Excellent. Glad to hear that.

Closing.
