### ISSUE TITLE
Missing stream quality?

### ISSUE THREAD

**Issue by C44Supra** [aqw/xbmc-gamepass#306]
Just installed the add-on, works great so far. However, the highest quality stream I get to chose is 4968882 kbps, most likely 720p-ish.  However, when I play the same game on my iPhone and then cast it to my Chromecast on the same TV I can see a clear as day difference in quality. NFL Gamepass Europe did state that their max would be "full HD 1080p" at a bitrate of "6000 Mbps". I'm going to guess that's what I'm getting with the iPhone / Chromecast combination.

I'm running OSMC / Kodi 17.3 on a Raspberry Pi 2B.

**Comment by kaileu** [comment]
If its 1080p i am not sure but you are right.

**Comment by kaileu** [comment]
@C44Supra please test the new Master

**Comment by BaumSchorle** [comment]
It is still 720p but with higher bitrate which results in smoother playback

**Comment by Donl5355** [comment]
I now have 1080p at 29.970fps

**Comment by BaumSchorle** [comment]
maybe it depends on the game and/or show!?

**Comment by Donl5355** [comment]
i tried it with nfln live the first episode of hard knocks and the steelers vs giants game from last night

**Comment by Donl5355** [comment]
are the 60 fps streams still microsoft exclusive?

**Comment by kaileu** [comment]
I don't think there is a 60fps stream available anymore.

**Comment by grumb3l** [comment]
Yes they are. You can watch 60fps games in the NFL app on Windows 10 for example.

**Comment by kaileu** [comment]
@grumb3l in which country you are?
At the moment there isn't a compatible app in the Windows 10 app store for me.

**Comment by Displayel** [comment]
@kaileu thats right no compatible app for W10 and no compatible app at the google play store for nvidia shield, which is pretty lame, without you guys i would have one of the most powerful streaming boxes on the market and would not be able to watch NFL on my big screen

**Comment by aqw** [comment]
@C44Supra Can you retest with latest master?

@grumb3l So, you're seeing 60 fps in the official Win 10 App? If so, can you do some network sniffing/spelunking to take a look at what the manifest looks like and what format they're requesting?

---Alex

**Comment by C44Supra** [comment]
@aqw I tested the master right after @kaileu told me to. The ~6000kbps stream showed up and worked great. I see that the only difference from that commit to the latest one is some cleanup. I'll install and test that one later tonight =) I'd be interested in the 60fps versions too but iirc that's only for select games? I'm in Germany as well but I only run Mac and Ubuntu (Kodi on OSMC on a RPi2B).

**Comment by Donl5355** [comment]
Found the nfl on windows app in the us store. https://www.microsoft.com/en-us/store/p/nfl-on-windows/9nblggh1z3cf

**Comment by aqw** [comment]
@C44Supra Glad to hear it's working.

@Donl5355 Are you in the US? If so, can you install the app and take a look at the streams to see what's going on?

---Alex

**Comment by Donl5355** [comment]
I'm in switzerland and can install it.

**Comment by Ghoschdi** [comment]
@aqw: I just tested the NFL on windows app and it works in Germany as well. Provide your GP credentials in the settings and you can watch GP games and agree, they look like 60fps version which XBox One played last season.

**Comment by aqw** [comment]
@Donl5355 @Ghoschdi can either of you take a look at the network traffic and figure out what video format they're requesting in order to get access to those streams?

**Comment by Donl5355** [comment]
http://nfl-vod191.xboxlive.com/nlds_vod/nflxbox/vod/2017/08/11/37178/1_37178_pit_nyg_2017_b_whole_1_6000_ced.mp4.m3u8 i dont know if that helps. i'm not that familiar with wireshark.

**Comment by aqw** [comment]
@Donl5355 We're interested in what parameters the client sends to the servers to get a list that contains that m3u8 file.

**Comment by Donl5355** [comment]
@aqw how/where do i get this info?

**Comment by Ghoschdi** [comment]
@aqw: https://github.com/aqw/xbmc-gamepass/issues/227#issuecomment-247503194 

This has not changed, still the same tokens and SHA1 HMAC.

**Comment by aqw** [comment]
@Ghoschdi Ahh, ok. So we'll have to continue to live without 60 fps.

Thanks for the info. :-)

---Alex

**Comment by kaileu** [comment]
I think its a server based authentification.
The reason we are not able to see the original response is that its SSL encrypted.
So if someone is able to capture a plain Text Dump. Let me know.

Mit freundlichen Grüßen
Kai Leutner
