### ISSUE TITLE
App Will Not Launch

### ISSUE THREAD

**Issue by CitrusPlayer** [aqw/xbmc-gamepass#311]
Hi 

Thank you for saving us from the new web interface!

I'm using Krypton17.3 on Pi and have downloaded the addon from your web site as a zip and within Krypton I have installed the addon from zip. I have added my GP credentials and yet when I click on the icon to access GP nothing happens. I will format and reinstall from scratch as it might be my end however I thought I should raise here in case you have some wisdom to share/corret the issue. I shall report back.

Many thanks

G

**Comment by CitrusPlayer** [comment]
I forgot to mention, I also pre installed the underlying pre requisets prior to installing GP addon.

**Comment by kaileu** [comment]
Please enable debug Logging and post a full debug log

Mit freundlichen Grüßen
Kai Leutner

**Comment by msmittag** [comment]
Sorry for bothering you again.

Same problem here - addon will just not start. Will get back to you with details later but I run latest openelec system with latest Kodi on Raspberry Pi. Addon version is Daunte Culpepper.

Greetings
Michael

**Comment by kaileu** [comment]
Same for you @msmittag install latest version from git and if it fails upload a full log with debug logging enable.

Mit freundlichen Grüßen
Kai Leutner

**Comment by msmittag** [comment]
Hey folks,

again - thanks so much for your help. I just downloaded the Jay Cutler version and installed from ZIP - which works!
@CitrusPlayer - I recommend you do the same.

Who would have thought that Jay Cutler would solve my problem...   ;-)

Cheers
Michael

**Comment by CitrusPlayer** [comment]
Hey, great news msmittag!  Sorry for the silly question but where do I get the Jay Cutler version? 

Thanks

-----Original Message-----

**Comment by aqw** [comment]
@msmittag I'm glad someone else found the Jay Cutler naming to be amusing. I figured it would be an appropriate name for what it likely to be a bug-ridden and unreliable release. ;-)

@CitrusPlayer Download the latest master (main page, right side "Clone or Download"), and that will give you the latest code (which will eventually become the Jay Cutler release).

---Alex

**Comment by CitrusPlayer** [comment]
Thank you Alex, however this is exactly what I did on Sat night. Has the build changed since then?

Cheers

-----Original Message-----

**Comment by aqw** [comment]
@CitrusPlayer The build has changed since then, though depending on where/when "Sat Night" is for you, it has changed to a varying extent.

I recommend trying the latest. If you still have a problem, do as @kaileu suggested and provide a full debug log.

---Alex

**Comment by CitrusPlayer** [comment]
Sweet sweet music! Never before have I been so pleased to see the "Jay Cutler Release"... The app now launches and working. Great work guys! I love having so much choice over video quality, dont ever take that away please :) 

Game in 40 in the plan?

Many thanks

**Comment by kaileu** [comment]
What did you mean with Game in 40 in the Plan?
If you mean the Summarized version its already in there. Check your setting for prefered type amd set it to ask.

Mit freundlichen Grüßen
Kai Leutner

**Comment by aqw** [comment]
@CitrusPlayer Glad t hear it's working for you. :-)

As @kaileu said, "Game in 40" is already available. Check your settings. :-)

---Alex
