### ISSUE TITLE
game pass international start develop

### ISSUE THREAD

**Issue by dav-sap** [aqw/xbmc-gamepass#314]
hey guys, 
I'm willing to start helping for the international version.
I can use a bit of help so anything will be appreciated. 
Which version should we sniff packets from? iPad? Android?
I have Android so i can do that.

Let's get started.

**Comment by aqw** [comment]
@dav-sap Issue #313 discusses the background and starting point for Game Pass International support. Please read that, and if you feel you have the necessary time, effort, and skills, we'd be delighted to work with you to help make it happen.

---Alex

Closing as dup of #313
