### ISSUE TITLE
Hide game length

### ISSUE THREAD

**Issue by jbarry786** [aqw/xbmc-gamepass#315]
****EDIT - I know realise that this is meant for the main menu of games. So I am going to edit it this to request for the game length to be omitted when you play any particular game. **** 

![image](https://user-images.githubusercontent.com/30951795/29270968-154d2e1e-80f1-11e7-82c0-8f5817454c63.png)

Still shows the game length when you stream a vod game.
![image](https://user-images.githubusercontent.com/30951795/29270996-380736d4-80f1-11e7-882f-3ffe6e218004.png)

Is it possible to also hide the playing time when you actually click to stream a game?

For people like me who freak out about any thing that potentially spoils a game, this is a big one.  If the game has a normal length -> no OT. If it has an extended length -> high chance of OT. Basically, either way you will be spoiled. At least I am :).

Thanks

**Comment by aqw** [comment]
@jbarry786 Thanks for the bug report/feature request. I don't know of any way to have Kodi suppress the display of the stream duration in the video playback mode. We just hand the stream to Kodi and it uses whatever the skin has defined for the playback UI. We have no control over that.

Maybe, far in the future, when Kodi cleans up its concept of Skinned Addons and gives us more control, then we could do this. But considering we can't even define our own font right now... I wouldn't hold my breath.

---Alex
