### ISSUE TITLE
Login isssue

### ISSUE THREAD

**Issue by slh1984** [aqw/xbmc-gamepass#316]
I am using the master zip on version 17.3 and have a active gamepass subscription however when I click on the add on I get login error. I also know of 2 other people with this issue. Any help would be greatly appreciated thanks. It is gamepass Europe and am in the uk

**Comment by kaileu** [comment]
Please post a log.....

Mit freundlichen Grüßen
Kai Leutner

**Comment by aqw** [comment]
@slh1984 To quote the text that you saw while reporting this issue (as we auto-fill the "new issue" window with it):

> If you are reporting a bug, please enable debugging and provide Kodi's log
> file. For instructions on how to do this, please read
> http://kodi.wiki/view/Log_file

---Alex

**Comment by aqw** [comment]
@slh1984 Closing. If you are still having this problem, please enable debugging and provide us with the debug log.

---Alex
