### ISSUE TITLE
Extreme lag

### ISSUE THREAD

**Issue by HenioH** [aqw/xbmc-gamepass#325]
Is anyone else experiencing sever buffering on NFL Network and Live Games? I have never had buffering issues with this addon within the last two years since the last couple days. I reset my connection, restarted Kodi, did all the usual but still getting sever buffering and freezing. Only started after recent update. Last week played perfectly.

**Comment by Ghoschdi** [comment]
My first guess is that they are not related directly to the addon but rather with one of the other options.

1. this season has a new max bandwidth setting (higher resolution), causing some challenges with connections of some folks. Colleague had the same issues as you and had to switch back on bandwidth class
2. issues on the provider side, which i encountered twice since the switch but only with minor impact

**Comment by HenioH** [comment]
I tried the lowest bitrate and still after 15-20 secs getting tons of bufferring. When watching something else even in 4k or 1080 I get no buffering whatsoever. Seems to play fine for about 20 secs then freezes and buffers consistently. Getting download speeds of 185mbs should be more than enough.. any thoughts on how to stop the buffering?

**Comment by Displayel** [comment]
i think since the preseason started i did NOT had one buffer yet, its running very smoothly

**Comment by whitesnuf** [comment]
Have you tried to clear the video chache from Kodi? It helped me with my buffering problems.

**Comment by HenioH** [comment]
Deleted cache to no luck. Since this week of preseason games have had only buffering on live games and live nfl network. Prior it would run perfect with no issues whatsoever. I did turn off the accelerations and it helps more and not as much buffering but still more than 50% of the time watching is buffering. I know we are not supposed to talk about Proxies but any recommendations  on a good one. Wonder if it could be the one I have been using for the past 2 years finally having issues with the new nfl servers.

**Comment by whitesnuf** [comment]
One more thing to try is increasing the Kodi video cache:

http://kodi.wiki/view/HOW-TO%3AModify_the_video_cache

**Comment by HenioH** [comment]
Thanks whitesnuf but I have an advancedsetting.xml in place for buffer cache but still no luck. frustrating since the last two seasons played flawless with no buffering.

**Comment by whitesnuf** [comment]
Ah, okay. 

You know, that since Kodi 17 the logic in it has changed a bit?

**Comment by HenioH** [comment]
Ya been reading the other issue and support tickets. Wish I understood it more to help out.

**Comment by HenioH** [comment]
so far on the lower 1545kbps stream or under are the only ones that stream without buffering. Sucks as prior season live streams in the highest stream would play perfect..

**Comment by kaileu** [comment]
If i am right you are using a vpn to bypass region restriction don't you?
So its a problem with your vpn not with the addon.

**Comment by HenioH** [comment]
I've tried several Proxy providers and same results with each. Tried a variety of other content from other addons and no buffering as well as other sport addons. Im in the USA if that sheds any light. Its strange as I've never had buffering within the GamePass addon while live in previous seasons.

**Comment by kaileu** [comment]
The Content is for Europe People only.
And therefore the peering conditions should be really bad for other People.

I think thats the reason why its not working good. Nevertheless please use Gamepass International if you are inside US. 

Mit freundlichen Grüßen
Kai Leutner

**Comment by aqw** [comment]
@HenioH @kaileu Please do not discuss, support, encourage, troubleshoot, in any way, any method of getting around Game Pass's region restrictions here.

They are a common cause of performance problems, are a waste of our time to diagnose, and put the project at a legal risk.

I will delete the above comments and close this issue.

---Alex

**Comment by Ghoschdi** [comment]
@aqw: I know you try to stay away from this, but does it make sense to add a positive message to the readme or at least to the new issue form, e.g. stating: "The addon and our staff only support residents to access the Game Pass service within their respective regions & GP's T&C, e.g. European residents accessing Game Pass Europe?"

**Comment by aqw** [comment]
@Ghoschdi Do you mean something like:

```
<!--- We do not support setups which attempt to circumvent region restrictions
      (proxies, etc) as it is against NFL Game Pass's Terms of Service. -->
```

That's auto inserted as the first line of every new issue opened. ;-)

---Alex

**Comment by jake404** [comment]
I'm in Sweden with no VPN on a 100/100 connection and it buffers for me as well. Yesterday I was watching an archived game and it buffered 6 times.

**Comment by Ghoschdi** [comment]
Oh, sorry for that - seems like I did not open a new issue quite some time :) 
*shrug* people just do not read what you write :(

@jake404: I had the same, but it is definitely not the addon, it is the platform. It was gone yesterday night. Have friends who use the official Apple app and encountered the same yesterday. Seems like the platform was a bit overloaded and they might add more capacity.

**Comment by aqw** [comment]
@Ghoschdi yeah, those statements in the new issue dialog (don't use/discuss proxies; be sure to provide debug log) is what gives me room to be less patient with those who choose to not read/ignore those requirements. :-)

@jake404 It took NeuLion years before they could reliably handle the traffic. I won't be surprised if WPP/Bruin have growing pains.

**Comment by kaileu** [comment]
@aqw in the End they are using akamai as the underlying CDN. But i think they have to pay a bit more for the Bandwidth. I think they didn't expect as much traffic during PreSeason.

Mit freundlichen Grüßen
Kai Leutner

**Comment by jake404** [comment]
Ok, I will wait and hope they fix most of the issues before the regular season.

Please don't censor this forum. I just wrote that I **didn't** use the V word and you edited my post. I understand that using the V word is against policies... but people aren't idiots. They know what measures are out there. It's better to just close the topic.

**Comment by aqw** [comment]
@jake404 You and I both know how search engines work.

You and I both know that corporate lawyers have no sense of humor no any willingness to be understanding. They're told to protect their corporation's IP, and that's the end of discussion. Shut down.

I don't care at all what people do on their own setups; I have absolutely no emotional attachment to that. What does concern me is that Kodi has a hard-to-shed reputation for piracy and that lawyers will see this project as an attempt to promote the piracy of streams and circumventing of their restrictions.

Thus all mentions of any of that is completely, 100% verboten.

I edited your post because it had useful information, but I didn't want the search term there.

You will also notice, that this issue is closed. if you want me to lock it also, I sure can.

---Alex
