### ISSUE TITLE
Domestic Game Pass Support

### ISSUE THREAD

**Issue by ShonKable** [aqw/xbmc-gamepass#329]

**Comment by ShonKable** [comment]
The last Edition was Domestic, is there anyway to get it back.... My Password dont work on Inter.

**Comment by kaileu** [comment]
@Sean Arnold ist working on this.

Mit freundlichen Grüßen
Kai Leutner

**Comment by aqw** [comment]
@ShonKabel Is there a Game Pass Domestic service? A user had told me that the service as being retired.

If there is indeed a Game Pass Domestic service, it /likely/ will be supported once we get Game Pass International working.

---Alex

**Comment by gallatin** [comment]
Hi,

I'm not sure what the service is *called*, but I'm a US "Game Pass" subscriber.  From a quick check of the chrome dev tools on the NFL game pass web page page when playing back a game, it uses https://neulionms-a.akamaihd.net/nfl/gamepass/v2/nflgp/site_4/scripts/header.js, so I think it maybe has something in common with the International version..?

Please save me from the horrible android tv app..

**Comment by ShonKable** [comment]
This stuff is just a little too advanced for me. I'm looking for someone to get the NFL Game Pass working and re zip it for us to download.

**Comment by aqw** [comment]
@gallatin Ahh, thanks for the info. Someone else (can't remember who) said that there was no longer Game Pass in the US. I wish Game Pass would just publish a damn list...

@ShonKable We don't have Game Pass International/Domestic support right now. There is an effort in #313 to make that happen.

These things take time and are hard, but the hope is to get this working before the regular season.

---Alex
