### ISSUE TITLE
Archived Games won't playing anymore

### ISSUE THREAD

**Issue by whitesnuf** [aqw/xbmc-gamepass#330]
[kodilog.txt](https://github.com/aqw/xbmc-gamepass/files/1242534/kodilog.txt)

 
I receive an error message every time I try to start an archived game. Nfl Network runs without problems.

**Comment by Baranethir** [comment]
Here also the same problem.

**Comment by messiuw** [comment]
Im having the same problem. It also says on the menubar "Gamepass International" and I do have the possibility to watch games up until 2011, which should not be possible with Gamepass Europe.

**Comment by TweekDash** [comment]
having same issue, happy to provide log if needed

**Comment by kaileu** [comment]
@emilsvennesson https://github.com/aqw/xbmc-gamepass/blob/7e405ee06fd75993d9d4b49b412b817bda930945/resources/lib/pigskin.py#L225 here is the new Problem the NFL added here another Analytics json field which has to be skipped.
Your for Loop is a bit to complex for me to Change it directly:

```
games = []
for x in games_data['modules']:
    if x == 'analytics':
        continue
    for g in games_data['modules'][x]['content']:
        games.append(g)
```
This fix should work.
I can't do a PR because my Windows crashed and Needs a bit to get fixed

**Comment by HenioH** [comment]
Having the same issue here. Would test out above code but not to familiar on how to enter it in correctly. Tried but got "Gamepass Error"

**Comment by kaileu** [comment]
@HenioH
You are not allowed to use a tabulator instead use 4 whitespaces for each tab.
Then the indention error should gone.

**Comment by HenioH** [comment]
Got it working. Thanks @kaileu

**Comment by TweekDash** [comment]
thank you @kaileu I got this working too.

If anyone needs any help with how it should look exactly this is it and as kaileu noted use lots of spaces
`            games = [] 
            for x in games_data['modules']:
                if x == 'analytics':
                    continue
                for g in games_data['modules'][x]['content']:
                    games.append(g)	
`

screenshot:
![image](https://user-images.githubusercontent.com/7328474/29586264-4b759452-8747-11e7-9695-967b3775d61a.png)

**Comment by emilsvennesson** [comment]
@kaileu Thanks for looking into it! I have PR:d a fix at #331.

**Comment by Displayel** [comment]
so which program do you use to open the pigskin.py and then which line is the one that needs to be edited in this picture above ?

**Comment by TweekDash** [comment]
i used notepad++, it's free the line to replace was called out by kaileu 225

`             games = [g for x in games_data['modules'].keys() for g in games_data['modules'][x]['content']] `

although it looks like emilsvennesson simplified that line in his pull request fix it probably works now too

**Comment by Displayel** [comment]
yes got it to work thanks man

**Comment by ShonKable** [comment]
Is there anyway Kaileu can upload the fixed Game Pass in a new zip file... Please... I love NFL... how can i get it to work??

**Comment by ShonKable** [comment]
With notebook is this in the default.py ???

**Comment by TweekDash** [comment]
what OS is your kodi install on? i'll give you the full path to the file @ShonKable should make it pretty easy

**Comment by ShonKable** [comment]
Ok i dont see a pigskin py... where do u find that? I only have default py ???? Please help

**Comment by TweekDash** [comment]
are you looking in the plugin directory under gamepass? /resources/lib/pigskin.py

**Comment by ShonKable** [comment]
I use notepad++

**Comment by ShonKable** [comment]
Im trying kodi 16 and 17

**Comment by TweekDash** [comment]
is your kodi installed on Windows? Linux? Mac? Android?

**Comment by ShonKable** [comment]
android .. but i have the addon extracted on my windows cpu

**Comment by ShonKable** [comment]
I have went through this whole addon .. I dont see anything that says "Pigskin py" ...arrgggggg

**Comment by ShonKable** [comment]
wwooeeeeee... I found it ..!!!!

**Comment by aqw** [comment]
@ShonKable This is a developer forum, not IRC for your stream-of-conciousness.

Everything you post here is emailed to a lot of people's inboxes.

Please respect that.

Thanks to @whitesnuf for the debug report w/ debug log :-) and @kaileu and @emilsvennesson for running this issue down.

---Alex
