### ISSUE TITLE
Unexpected error='(.Please enable debuging for both addon and Kodi??   WTF 

### ISSUE THREAD

**Issue by ShonKable** [aqw/xbmc-gamepass#332]

**Comment by aia832003** [comment]
I'm seeing this on Android but not the Linux client.

**Comment by ShonKable** [comment]
I use android ??? Hopefully there is a fix and an update soon

**Comment by aia832003** [comment]
Ok. I'm getting this on both clients now.

**Comment by ShonKable** [comment]
Thx.. Im willing to donate and get that Cam Newton Version... : )

**Comment by kaileu** [comment]
Install from master and wait on the pr to be merged.
Don't change the files by hand if you don't know what you are doing.

**Comment by ShonKable** [comment]
pr ???

**Comment by kaileu** [comment]
PR means Pull Request.
In other words wait till the fix is in the master version.
To manually edit files is not supported here.

**Comment by ShonKable** [comment]
Ok thx sir, any time frame?

**Comment by aqw** [comment]
Dupe of #330
