### ISSUE TITLE
Condensed games not working

### ISSUE THREAD

**Issue by jake404** [aqw/xbmc-gamepass#335]
Can anyone else here play the condensed games? It doesn't work for me... everything else works.

Here is the debug file: https://pastebin.com/P8GBj052

**Comment by whitesnuf** [comment]
I can watch them without problems.

**Comment by kaileu** [comment]
@jake404 it Looks like a Proxy/Network Problem or something like that.
The Addon itself works but you can't open the stream because of corruptness or if you managed  to open then ist failed to Play.

**Comment by jake404** [comment]
If it was a network issue then I would have problems with the full games and the live stream, but they work fine. I guess we'll have to blame Deltatre.

**Comment by aqw** [comment]
@jake404 Glad it's working for you now. :-)

---Alex

**Comment by jake404** [comment]
It's not working... I closed the issue because you said it wasn't a problem with the addon.

**Comment by aqw** [comment]
@jake404 Ahh, sorry. My bad. I misread. :-/

Odd that you're having problems, as all stream types work for me perfectly. Do you have "InputStream" enabled in your settings? If so, try disabling it. It's unlikely, but possibly the condensed stream being returned just doesn't play nicely...

---Alex

**Comment by jake404** [comment]
I have tested both with InputStream on and off.

After some more testing it seems to be only certain games. 

Some examples:

Packers vs Redskins - Works
Patriots vs Texans - Doesn't work
Ravens vs Dolphins - Doesn't work
Giants vs Browns - Works

**Comment by aqw** [comment]
@jake404 Hmm... all of those games work for me, both full and condensed. Do you have a particular bitrate set? I tried a few bit rates, but they all worked...

**Comment by aqw** [comment]
@jake404 Yeah... the Input Stream setting not-saving is because your install of Kodi doesn't have InputStream support. The addon silently disables it, but it really would be better if the user was informed via a dialog.

it's on our list of known-suboptimal-things. ;-)

---Alex

**Comment by jake404** [comment]
Hmm, after your comment I Googled InputStream and found out that it's disabled by default in Kodi and after enabling it the condensed games work.

**Comment by aqw** [comment]
@jake404 That's.... unexpected. @emilsvennesson You know know more about InputStream than I. Am I missing something here?

@jake404 But I'm glad it's working now. :-)

---Alex

**Comment by emilsvennesson** [comment]
I have also found inputstream.adaptive to be much more reliable and faster than ffmpeg. I find it odd that it's not working at all with ffmpeg though...

I should also add that 17.4 was just released and that version includes an up-to-date version of inputstream.adaptive that works with Game Pass. :-) It's being shipped as disabled by default for some reason, so be sure to enable the add-on in the settings.

**Comment by jake404** [comment]
@emilsvennesson does InputStream set quality only when you start the stream or does it change dynamically while watching the stream?

**Comment by emilsvennesson** [comment]
@jake404 It's fixed for now but adaptive bitrate switching is coming in the future. You can change the min/max bandwidth as well as max resolution in the inputstream.adaptive settings.

**Comment by jake404** [comment]
Good stuff @emilsvennesson and thanks!

Thanks @aqw !
