### ISSUE TITLE
Sound gets increasingly out-of-sync

### ISSUE THREAD

**Issue by baddazz** [aqw/xbmc-gamepass#338]
When I play one of the featured videos (like Hard Knocks) the audio slowly gets more and more out-of-sync.
Any ideas why this would be and how to solve the issue?

Thanks.

**Comment by Ghoschdi** [comment]
Have not experienced that, but have not watched Hard Knocks and only GMFB so far. 
Which platform do you run Kodi on and which video player do you use (FFMPEG or InputStream?)

**Comment by kaileu** [comment]
I found the same behavior in the oldest Superbowl game.
I just haven't the time to investigate it.

Mit freundlichen Grüßen
Kai Leutner

**Comment by jmhotham** [comment]
This may be independent of the add-on. I was watching Hard Knocks last week on my Android device just running the GamePass App and the sound was also out of sync. Haven't notice any problems with games though.

**Comment by aqw** [comment]
@kaileu @baddazz Can you reproduce this in the web interface? We should know whether it's our fault or not, and @jmhotham's comment seems to indicate that it might be GamePass's fault.

---Alex

**Comment by baddazz** [comment]
My Kodi runs on a Pi3 and right now i'm using InputStream. I gonna try to deactivate the InputStream Addon. Maybe FFMPEG work's better...
@aqw Over the Gamepass Website everything's fine and on my Android Cellphone with the Gamepass App to.

**Comment by aqw** [comment]
@baddazz Is this still a problem for you?

---Alex

**Comment by aqw** [comment]
Closing stale issue.
