### ISSUE TITLE
buffering/hanging issue

### ISSUE THREAD

**Issue by chrisbear78** [aqw/xbmc-gamepass#342]
http://paste.ubuntu.com/25488828/

Hi gamepass keeps freezing and something hanging, it's because it's buffereing. happens at lots of different stream qualities, I've the following settings in advancedsettings.xml 

buffermode 1
cachemembuffersize90000000
readbufferfactor10
  

and I'm running it on Rpi2 on openelec Krypton 

Any ideas? also current download speed tests at about 71Mbps

**Comment by CitrusPlayer** [comment]
Same platform, same issue. Would a log help?

**Comment by kaileu** [comment]
A full log is always helpfull.

**Comment by chrisbear78** [comment]
Yea I'm still getting the same problem, also did I do something wrong when posting the original issue?

**Comment by kaileu** [comment]
Your log didn't even contain some output from the addon.

**Comment by chrisbear78** [comment]
Well thanks for letting me know, that was really helpful.

It should have done since it was the log from when i was running the addon

**Comment by kaileu** [comment]
My guess you don't enable Debug logging in Kodi and in the addon.
09:22:25.438 T:1946968080  NOTICE: Disabled debug logging due to GUI setting. Level -1.

**Comment by chrisbear78** [comment]
Cool thanks.

**Comment by ShonKable** [comment]
Are there any editions out that will allow me to watch replays and the USA not interested in live just replays..??? PLEASE HELP

**Comment by kaileu** [comment]
The only official port as far as i know is the one from Sean.
There are possibilities but none of them is legal.

Mit freundlichen Grüßen
Kai Leutner

**Comment by ShonKable** [comment]
Ok i need the one from Sean.. i have an account... How to i get Sean's edition ??

**Comment by aqw** [comment]
@chrisbear78 Is this still an issue for you? If so, please enable debugging and provide the log.

@ShonKable First off, please don't hijack other people's issues. It's rude. In answer to your question: I know Sean has worked on the support, but I don't know how far he got. We're (hopefully very soon) going to make changes to the addon that will allow him to integrate International support when that is completed.

---Alex

**Comment by chrisbear78** [comment]
@aqw 
Hi Alex,

I've not used that system to watch Gamepass since, I booted up my gaming PC last Sunday. Once I get a bit of free time I'll set logging and see what it is like.

Thanks for chasing it up :-)

Chris

**Comment by aqw** [comment]
@chrisbear78 Excellent. Also, please be sure to update to the latest version of the addon when you do get some time to retest it. :-)

**Comment by ShonKable** [comment]
What is the latest version ?? and can i use it with my account on the US?

**Comment by ShonKable** [comment]
When can qe get a 11.2 with US support

**Comment by kaileu** [comment]
Here you won't get a version for US there are two diffrent addons at the moment.
And it takes some time till it will be one unified version.

Mit freundlichen Grüßen
Kai Leutner

**Comment by ShonKable** [comment]
Ok guess ill check back next year :(  (sad face)

**Comment by kaileu** [comment]
Try to checkout Seans git and try it if something is wrong open up an issue on his github.
If its unified then we can combine it.

Mit freundlichen Grüßen
Kai Leutner

**Comment by CitrusPlayer** [comment]
Hi Guys,

Sorry for the delay. I tested nfl network live last night, it was good. I shall test again directly with live games tonight and let you know if I still have an issue, in which case I shall find out how to provide you a meaningful log. Thanks again for your work and have a great night watching game.

Cheers

**Comment by aqw** [comment]
@CitrusPlayer Glad to hear it's working for you. I also tried last night, and everything was just fine for me.

@chrisbear78 Any luck for you?

---Alex

**Comment by aqw** [comment]
Closing old issues from last season. I assume this issue was part of Game Pass Europe's streaming difficulties last year and is resolved now. If this is still an issue, feel free to reopen and include a debug log.

---Alex
