### ISSUE TITLE
Red Zone Live Not Working

### ISSUE THREAD

**Issue by HenioH** [aqw/xbmc-gamepass#343]
Everything works accept RedZone Live? Anyone else have this issue? Cant currently supply log where i'm at just wanted to bring to attention.

**Comment by kaileu** [comment]
What you mean with RedZone Live?
There is no RedZone Live at the moment maybe in a few hours.
See picture below of the Gamepass App.


Mit freundlichen Grüßen
Kai Leutner

**Comment by HenioH** [comment]
Just realized its still 30 mins till actual kickoff of todays games. I was showing Redzone Already under NFL Network but of course it wouldnt play if there are no live games.  This can be deleted. Apologize again.

**Comment by playpauseandstop** [comment]
Unfortunately NFL RedZone - LIVE still not working for me in Kodi plugin, but works in web browser. Seems like NFL changes the URLs for RedZone streams.

**Comment by redhell** [comment]
Doesn't work for me either

**Comment by flabernak** [comment]
Same here. Link is there just errors out

**Comment by ppetermair** [comment]
+1

"Unexpected error='(.Please enable debugging in Kodi and submit a bug report."

**Comment by kaileu** [comment]
Guys stop spamming please.
Its not working and i am looking into this.

Mit freundlichen Grüßen
Kai Leutner

**Comment by Tuxglux** [comment]
Thanks for quick fix.

**Comment by emilsvennesson** [comment]
I think we'd all appreciate if everyone could stop with the 'it's not working for me either' posts. They are not helpful at all from a developer standpoint seeing as neither of you posted a debug log.

Thanks a lot @kaileu. Closing as this issue was fixed by d4cc6560d43a34a52a7f0bb11cb06eda2b2ee577.

**Comment by nicelub** [comment]
hello, can you please help me how i can use this fix? I have raspberry pi3 with libreelec. I installed yours nfl game pass and red zone live did not work. I dont know where to put this edited file in raspberry.

Can you help me pls? Thank you very much

**Comment by redhell** [comment]
Download the (master) zip and install it in kodi.
