### ISSUE TITLE
Feature Request: Make Redzone Replay available

### ISSUE THREAD

**Issue by whitesnuf** [aqw/xbmc-gamepass#346]
The replay from the Redzone Channel is available on Gamepass Homepage

Is there a chance to implement it in this great addon?

![redzone replay](https://user-images.githubusercontent.com/20865586/30377113-f553c982-988e-11e7-9c2c-797bdcbe560e.jpg)

**Comment by aqw** [comment]
@whitesnuf Thanks for letting up known about the feature, and thanks to @kaileu for the patch adding support. :-)

---Alex
