### ISSUE TITLE
v11.1 not in SPMC Kodi Repository

### ISSUE THREAD

**Issue by SullyCT79** [aqw/xbmc-gamepass#348]
How can I install the latest version on SPMC?  I believe v9.2 is only available.

**Comment by kaileu** [comment]
Its not compatible with spmc because spmc is not based on a current Kodi.
You could try the current beta of spmc.

Mit freundlichen Grüßen
Kai Leutner

**Comment by aqw** [comment]
Closing. As @kaileu said, it's an SPMC compatibility issue.
