### ISSUE TITLE
All Working but One Game

### ISSUE THREAD

**Issue by HenioH** [aqw/xbmc-gamepass#351]
Is anyone else not able to play the Patriots game? All other games start up and play perfectly, everything working except that one single game I get an unexpected error. I'm out away from my computer to send a log if anyone else is having this issue.

**Comment by whitesnuf** [comment]
For me the game works fine

**Comment by BaumSchorle** [comment]
are you in the UK? Is it broadcasted on Sky and therefore blacked out on
GamePass?

**Comment by kaileu** [comment]
I think thats the reason why its not working for him.
Please upload a log so we can see how blackout games are marked.

Mit freundlichen Grüßen
Kai Leutner

**Comment by HenioH** [comment]
Ya its strange I've never had just one game not work. Everything else works perfectly. I am in the USA if that explains "how I am using it" without saying it.

**Comment by HenioH** [comment]
Yes it was a sky blocked. I have remedied my issue. Thanks for the input.

**Comment by aqw** [comment]
@HenioH Glad to hear it's resolved. As @BaumSchorle asked, did you get a debug log of the block? It would be nice to know what it looks like to we can provide an informative error to the user.

---Alex

**Comment by aia832003** [comment]
I'm having the same issue. Playing in the USA, but one game a week refuses to play.

**Comment by kaileu** [comment]
Playing Gamepass Europe in the US is against the Tos ;-)

Mit freundlichen Grüßen
Kai Leutner
