### ISSUE TITLE
Missing episodes from NFL Network

### ISSUE THREAD

**Issue by jake404** [aqw/xbmc-gamepass#355]
Most of the programs under NFL Network won't list any episodes. For example 'Classic Games' and 'NFL Films' are empty. However if I check 'NFL Show' all episodes are there. If I check the Android app and the website they are all available. Anyone else have the same issue?

**Comment by kaileu** [comment]
See https://github.com/aqw/xbmc-gamepass/pull/354

**Comment by jake404** [comment]
Ok, thanks!
