### ISSUE TITLE
Remove "Final_Overtime"

### ISSUE THREAD

**Issue by jbarry786** [aqw/xbmc-gamepass#357]
Hi guys, 

is it possible to edit the code so that you do not get the information of "FINAL_OVERTIME" ?
![image](https://user-images.githubusercontent.com/30951795/30786836-04bb843a-a174-11e7-91e5-207138240825.png)

That is a huge spoiler not only for that particular game.... but for others as well, since if you only see "FINAL" in the others, you will know that they didn't go to overtime.

I would rather have no info whether the game was finished or not... over knowing it went to overtime.

Thank you

**Comment by Displayel** [comment]
also yesterday was a big mess, games were crashing back to the menu every 2-3 minutes, very frustrating yesterday, that was the first time this ever happened i believe

**Comment by kaileu** [comment]
Yes i noticed the same but i think it was a problem with Gamepass Servers. Sometime it works sometimes not. Some time every 2 Minutes then 40Minutes with no problem. It was really strange yesterday.

Mit freundlichen Grüßen
Kai Leutner

**Comment by GR3mGH0n** [comment]
jbarry786 is absolut right.
Please remove this annoying spoilers.

Thank you very much!

**Comment by darul86** [comment]
thx for this great addon, but this issue sucks really hard.

i changed it by myself in default.py
line 172 from  "game_info = game['phase']" to  "game_info = 'FINAL'"

**Comment by GR3mGH0n** [comment]
darul86 thank you very much!
I hope this change will be stitched into this fine addon.

**Comment by aqw** [comment]
Fixed by @pyrocumulus in #364, which is now merged.

Closing.
