### ISSUE TITLE
Logging into NFL Error

### ISSUE THREAD

**Issue by HenioH** [aqw/xbmc-gamepass#358]
Hello, I currently am getting a "Logging into NFL Game Pass failed. Make sure that your account info is correct and your sub is valid" issue. I went to the NFL Gamepass site and signed into my account without a problem but cannot get it to work within the addon. I have been using it since the beginning of the season without issue logging in. I have uninstalled cleared cache and reinstalled but same error with same login credentials I am using on the site. Any help would be appreciated.

**Comment by kaileu** [comment]
Without a log file we can‘t help ;-)

Mit freundlichen Grüßen
Kai Leutner

**Comment by kaileu** [comment]
Without a full debug log we can‘t help you sorry.

Mit freundlichen Grüßen
Kai Leutner

**Comment by HenioH** [comment]
From what I see says I don't have a valid Europe sub but have been using it since the begining of the season without  hitch till today.

[https://pastebin.com/eiUS3QdL](url)

**Comment by kaileu** [comment]
Maybe a problem with your ....

Mit freundlichen Grüßen
Kai Leutner

**Comment by HenioH** [comment]
Tried 7 different ..... and still same issue. They switched my sub to domestic!! had to resub with a euro now working with same ..... used earlier
