### ISSUE TITLE
Stream ends unexpectedly. Sporadic, no log available.

### ISSUE THREAD

**Issue by jmhotham** [aqw/xbmc-gamepass#360]
Hi guys,

the last two weeks I had an issue where the stream would be running fine and then suddenly cut out and take me back to the game selection screen. I was able to enter the stream once again, only to have it cut out sporadically some time later. This repeated about four times throughout the game, to a point where I couldn't re-enter the stream and got an "Unexpected error" message. I was not able to get the log as I didn't have debug logging enabled ( I will enable this for next weeks games). Obviously, without a log I don't expect any diagnostics, I was just hoping maybe someone else has experienced it and may have a idea what I can do to fix it? 

Cheers,
Jason

**Comment by kaileu** [comment]
The last time it was a problem with Gamepass Service itself

Mit freundlichen Grüßen
Kai Leutner

**Comment by jmhotham** [comment]
Thanks for the info, Kai. So this is a "known issue"?

**Comment by Displayel** [comment]
Yes its an NFL Issue, i received an apology mail 2 weeks ago, not this week, but i sure gave them a hate mail about this...unreal

**Comment by aqw** [comment]
Closing, as I agree that this was the fault of NFL GamePass. Hopefully this year is better...

---Alex
