### ISSUE TITLE
Nothing is playing

### ISSUE THREAD

**Issue by HenioH** [aqw/xbmc-gamepass#361]
Cant seem to play anything. Can access the NFL Game Pass but when I click on NFL Network select a stream nothing plays just stays on same screen to click on anything else with no error log same goes for all games under Gamepass. I have uninstalled and reinstalled as well as checked my account online and its fine. Any ideas would be appreciated.

**Comment by kaileu** [comment]
NFL Network Shows are most broken without my PR.
But if you want further investigation please post a log.

Mit freundlichen Grüßen
Kai Leutner

**Comment by HenioH** [comment]
Will post log but the live game right now I can select it then choose a stream quality and then nothing. not frozen just wont play without any error.

https://pastebin.com/raw/E1HzTYpk

**Comment by kaileu** [comment]
You are getting 403 errors.
(Forbidden messages)
As nobody else has this problems its you .... setup.

**Comment by kaileu** [comment]
You can send me email if you want to discuss a Support Sollution for your ongoing problems. I thinks its always the same problem at your site^^

**Comment by HenioH** [comment]
Yes please I've tried several ... and getting same issue. Any help would be greatly appreciated.

**Comment by kaileu** [comment]
Write me a mail git@kleutner.de.

Mit freundlichen Grüßen
Kai Leutner

> Am 06.10.2017 um 16:35 schrieb HenioH <notifications@github.com>:
> 
> Yes please I've tried several ... and getting same issue. Any help would be greatly appreciated. 
> 
>

**Comment by HenioH** [comment]
ok sent

**Comment by kaileu** [comment]
I am not sure if you recieved my mail 😅

Mit freundlichen Grüßen
Kai Leutner

**Comment by HenioH** [comment]
Just checked my Spam and it was in there...sent response

**Comment by ednorton75** [comment]
Hi, I'm having similar issues with NFL Gamepass international. I am subscribed and can use my account on my PC but when I try with Kodi It loads and then just says "working" but never stops.

i have  upgraded Kodi to 17.4, I have uninstalled NFL Gamepass app and reinstalled a few times. Nothing works. Any help would be appreciated. We are already week 5 so I'm worried I'll lose the whole season.

Thanks,

**Comment by HenioH** [comment]
Feel free to email me and I could explain what the issue might be and what it was for me. If thats not the case for you. You might want to upload a log to let one of the devs take a look.

**Comment by ednorton75** [comment]
HenioH - what's your email?

I'm at ednorton75@gmail.com

**Comment by aqw** [comment]
This seems to have been a user specific problem. Closing.

---Alex
