### ISSUE TITLE
NFL Int has been working for three weeks. Now not playing games.

### ISSUE THREAD

**Issue by webbr23** [aqw/xbmc-gamepass#362]
Hi,

The add on has been working for NFL International for that past three weeks or so but stopped playing games yesterday.  I can select year, week, game and then it errors.

I have attached the log.

Thanks for your efforts!

Ron
[kodi.log](https://github.com/aqw/xbmc-gamepass/files/1361938/kodi.log)

**Comment by kaileu** [comment]
Hi @webbr23,

For some reason you have no subscription.
GamePassError: u'not_entitled'.

**Comment by webbr23** [comment]
Hi,  I'm definitely subscribed.  The subscription works properly on web, IOS and Android.

Ron

**Comment by webbr23** [comment]
Further information;  If I run a VPN to to the UK, the add-on then works.  Without the VPN and originating from here in Kenya it does not work.

**Comment by kaileu** [comment]
Are you using the addon from here or a special international version from another dev?

Mit freundlichen Grüßen
Kai Leutner

**Comment by webbr23** [comment]
I'm using the addon from here - installed from the Kodi Repo.  V0.11.1

**Comment by fritsie82** [comment]
Finally.. by following the directions from the other thread #365 from @Ghoschdi I was able to get this to work.

From the Kodi home screen click Add-Ons > My Add-Ons
Scroll down and select VideoPlayer Input Stream
Select the InputStream Adaptive>click Enable
As @darul86 suggest if you need to install it try from the Krypton branch, I didn't need to as the version already installed worked fine.

**Comment by aqw** [comment]
This issue should be resolved now. If you believe this is still a problem, please reopen and upload a log.

---Alex
