### ISSUE TITLE
Finished games working fine, live games / NFL Network / RedZone not working

### ISSUE THREAD

**Issue by Prindle19** [aqw/xbmc-gamepass#366]
[GPLog.txt](https://github.com/aqw/xbmc-gamepass/files/1407578/GPLog.txt)

For the past 2 weeks, the archived games work fine, but I can not get any live games or NFL RedZone / NFL Network live to stream. 

Logs attached

**Comment by TweekDash** [comment]
this is the same as #363 and #365 which has now been solved

**Comment by aqw** [comment]
This issue should be resolved now. If you believe this is still a problem, please reopen and upload a log.

---Alex
