### ISSUE TITLE
[Solved] Games won't be played

### ISSUE THREAD

**Issue by Kreatief** [aqw/xbmc-gamepass#368]
I was using Kodi with the xmbc-gamepass addon fine until game 6. Now suddenly since week 7 I can not play any game anymore.
I see all games, I can click them and I do see the loading icon for about 1-2 seconds, the CPU load goes to about 90%, then it dissapears and I am still seeing the screen with the game list.

Logfile looks fine to me. I pasted the important part (from clicking the game until end) here: https://pastebin.com/d5W0M9B8

I also just downloaded the latest master and installed it from zip, which didnt solve the issue.

EDIT: oh and yes, I can login to my account and view games via a regular webbrowser.

**Comment by fritsie82** [comment]
Finally.. by following the directions from the other thread #365 from @Ghoschdi I was able to get this to work.

From the Kodi home screen click Add-Ons > My Add-Ons
Scroll down and select VideoPlayer Input Stream
Select the InputStream Adaptive>click Enable
As @darul86 suggest if you need to install it try from the Krypton branch, I didn't need to as the version already installed worked fine.

**Comment by Kreatief** [comment]
Perfect. This worked for me.
I had to install the newest Kodi (17.5.1) as you suggested. With the 17.4 it wouldn't work (popably due to the older version of the InputStream.

Thank you very much! Now it is time to watch all games from my team from weak 7 on... Time to take some vacation I guess.
