### ISSUE TITLE
[Problem] watch next Day(s)

### ISSUE THREAD

**Issue by Berulon** [aqw/xbmc-gamepass#372]
Hi,
i can watch life, and reduzone too, everything great but here in Europe it's very late to watch Thursday, Sunday or Monday Night games. So i want watch this next day when i come from work ... but not working

I can watch concendert Game, but not Game video, same one wekk laker with Coach game... only concendert will work... 

but there is no Error message..  i can chose the bitrate, but after nothing happend, only Video not start,

On website everything fine, but i want look on tv
any Ideas what happend?

**Comment by aqw** [comment]
Closing old issues form last season. If you believe this is still a problem, please reopen and upload a log.

---Alex
