### ISSUE TITLE
Crash on Startup

### ISSUE THREAD

**Issue by GR3mGH0n** [aqw/xbmc-gamepass#375]
Since yesterday the NFL Gamepass Addon crashed on startup. I upgraded to the latest 0.11.2 relase without any changes in behavior. I searched the log file and found "cookie_file". I gave it a try and renamed the file:

~/.kodi/userdata/addon_data/plugin.video.nfl.gamepass # mv cookie_file cookie_file.old

Now the Addon loads as expected again.
No new "cookie_file" was created.

**Comment by aqw** [comment]
@GR3mGH0n Glad it's working for you now. :-)

Closing.

---Alex
