### ISSUE TITLE
Kodi's GamePass needs a Project Leader for 2018

### ISSUE THREAD

**Issue by aqw** [aqw/xbmc-gamepass#380]
Hey Everyone,

So, I've been in denial about this for awhile, but I simply won't have the time to put the necessary effort into this addon this season. The annual breakage from changes to the GamePass service seem to have already started, so it seems I shouldn't put this off any longer...

What I'm looking for is someone (or someones) who is interested in taking responsibility for this addon this season. In addition to having the needed technical skills, it's also crucial that whoever steps up, that they are willing to accept the responsibility for working on this, and be willing to work on this through the season. Last year, this addon was download on average 500,000 times per release. That's a lot of users, and I don't want to leave them in the lurch.

The majority of the work is during the preseason (starting now) through the first week or two of the regular season. Then things start to slow down again.

If you are interested, feel free to either reply here or email me directly at alex@waite.eu.

I won't be entirely disappearing; I will be available to answer questions, provide pointers, and perhaps submit the occasional patch. But I won't be able to do heavy lifting as in the past.

---Alex

**Comment by emilsvennesson** [comment]
It's a shame you're no longer have the time to lead this project and I really hope someone else steps up to continue the development! You've done a great job. :-) 

I decided to not subscribe this year because of the steep price and the fact that they're still not offering 60 fps streams, otherwise I would have done my best to get this up and running again. It's a shame we never got started with the pigskin library discussed in https://github.com/aqw/xbmc-gamepass/issues/313 because that would have simplified a lot of things. Whoever decides to take this on also need to keep in mind that the code needs to become Python 3 compatible as soon as possible (see https://kodi.tv/article/attention-addon-developers-migration-python-3).

**Comment by kaileu** [comment]
I will update the Code as i notice that something is broken.
But i am not the right Person to Lead this Project because of my Lack of experience in Python.

**Comment by aqw** [comment]
@kaileu Thanks for the patches. I hope they keep coming. :-)

I wouldn't be too concerned about a lack of experience with Python. It matters, don't get me wrong. But when I started this project, I had very little experience with Python. What matters most is the way you approach the problem. If you're interested in getting better, a great way is to work on a real project.

So, my point is: don't let your inexperience hold you back. If this is something you feel you're interested in, and are willing to put time into, then I think it'd be a good fit. You've supplied patches for quite the while, and seem to be the only one doing so right now.

@emilsvennesson Thanks for the kind words, and as FYI, pigskin.py does exist, it just hasn't been split out into a separate repo. That, arguably, would help its visibility. If that's a blocker for anyone, I can certainly set that up, if that would get more involvement.

---Alex

**Comment by Displayel** [comment]
please guys if anyone could just fix the hiccup to make this season work again would be greatly appreciated...and i´m writing this without knowing how much work it is to fix the latest hiccup...

thanks guys.....

**Comment by kaileu** [comment]
@Displayel you can merge the fixes for which i made a pull request.
https://github.com/aqw/xbmc-gamepass/pull/381

Last night (my local time) it was working fine.

**Comment by aqw** [comment]
@Displayel I merged @kaileu's fixed. Pull the latest code. Perhaps it works.

**Comment by CraigMack69** [comment]
Well as a long time user back at the start :) i appreciate the work you have put into it alex. Truly and honestly. Whoever picks up this project. i can provide gamepass, EU, USA and INT versions. So any PY devs?

**Comment by aia832003** [comment]
Same as @Displayel on the HOF being the only games that will play without errors. I can also extend @CraigMack69 offer to help with INTL version login for those working on this great plugin.

**Comment by kaileu** [comment]
First of all please make an own Issue thread if you are having a problem.
@aia832003 did you test the latest Master with the merged code of https://github.com/aqw/xbmc-gamepass/pull/383?

**Comment by aia832003** [comment]
Yes. This is off the downloaded merged master from around 30 minutes ago. No live games until later tonight, but can test on those as well. Completed games are back to working on this new code merge. I was able to play all the games from last night. Worked on both Linux box and my Android TV.

**Comment by aqw** [comment]
@kaileu I've granted you push privileges to this repo. Thanks for all of the patches recently!

---Alex

**Comment by rva87** [comment]
I would be more then happy to help out/provide updates this season, however after this week I won't be able to do anything until mid september.

**Comment by aqw** [comment]
@rva87 Fantastic. Every bit helps, so we're happy for your time, whenever you can spare it. :-)

**Comment by aqw** [comment]
I think I can close this now. I've managed to get past many of the life blockers that have been competing for my attention. Much appreciation to everyone who stepped up to keep things working. :-)

Please don't take this to mean that I don't need help. There's a lot of work underway at the moment, and I need more help than ever making sure that too much breakage doesn't slip through the cracks. Every bit helps. :-)
