### ISSUE TITLE
Cut new release for preseason

### ISSUE THREAD

**Issue by aqw** [aqw/xbmc-gamepass#386]
Thanks to @rva87 and @kaileu, master is functional again! A new release should be cut so that the version in the Kodi repo enjoys the same.

I'm willing to do this, as it doesn't take too much time.

@kaileu, @rva87 and others: are there any additional patches you want to get in before the next release? Usually in the preseason there's multiple releases, so there's plenty of time for stuff to land, but if there's anything immediate you want in, I can hold off for a few days.

---Alex

**Comment by kaileu** [comment]
I think we can release a new version because now we have a working version.
The other PRs are more a visiual enhancement.

**Comment by rva87** [comment]
There is an issue with connection timeouts not being handled as well as they could (gamepass will hang for some minutes). I might be able to provide an update tomorrow. It's not critical though so if there is a plan tot push another release soon, i would not suggest to wait for this...

**Comment by aqw** [comment]
OK. Then I'll plan on cutting a release on Tuesday. That should give time for @rva87 to investigate the timeouts, but still get a release out quickly.

**Comment by rva87** [comment]
the update is ready(#387 ), my test looked good. @kaileu have some time to double check and test?

**Comment by aqw** [comment]
The release has been made and the PR is waiting: xbmc/repo-plugins#1985

---Alex

**Comment by aqw** [comment]
The PR has been merged, so users should be getting the 2018.08.15 release any time now.

**Comment by Displayel** [comment]
Hi, after i updated to this version i can´t login into the gamepass addon anymore, won´t let me in, there was this little fix done a week ago that made the preseason week 2 work again, this still works for me, but when i try this latest one it does not.
