### ISSUE TITLE
NFL Network episodes fill up

### ISSUE THREAD

**Issue by tinzarian** [aqw/xbmc-gamepass#395]
Not a big problem (it doesn't break anything, it's mostly cosmetic) but when refreshing the NFL Network shows the episodes start being listed multiple times.
To reproduce:
Click on the NFL Network logo t the top; it will scan the shows
Go to any show on the NFL Network tab; the episodes are listed
Go back up to the NFL Network logoand click on it; it will rescan the shows
Go back to the previously selected show; all episodes will be listed twice

**Comment by aqw** [comment]
@tinzarian Thanks for the bug report. @kaileu Any chance you could take a look at this, since you last touched that code?

**Comment by kaileu** [comment]
@aqw i am a bit busy at the moment.
I will try to take a look at the code on Monday.

A short guess is that i forgot to clear the Episode Variable or has to make sure thats a unique list.
I am not sure python can do this but o will look into it.

Mit freundlichen Grüßen
Kai Leutner

**Comment by aqw** [comment]
@kaileu No worries. We'll sure whoever gets to it first. :-)

---Alex
