### ISSUE TITLE
Wrong full game stream is played

### ISSUE THREAD

**Issue by tinzarian** [aqw/xbmc-gamepass#398]
I'm trying to play last nights game. The edited (without commercials) full game is available on the website, but the add-on plays the unedited version.
Debuglog is at: http://ix.io/1m9R

**Comment by kaileu** [comment]
Its just a timing Problem.
The Streams for the web ui is faster updated than the streams for the app.

Now 11:34 GMT+1 the streams are equal (without ads).

**Comment by tinzarian** [comment]
Ah ok, thanks, I'll close the issue.

**Comment by tinzarian** [comment]
I'm reopening this, because the same issue occurs. The edited stream without commercials is available on the website, and the android app. The stream the addon plays is with commercials.
