### ISSUE TITLE
Bring in latest Pigskin changes

### ISSUE THREAD

**Issue by aqw** [aqw/xbmc-gamepass#399]
Because of the Gigya auth changes, I had to merge in the changes from pigskin earlier than I wanted to.

I merged the patches in, fixed all the API breakage (i think), and through testing that, I am now banned by gigya. It seems too many authentications in quick succession results in a ban. The ban is initially short (5-10 min perhaps?) and gets progressively longer. [1]

So... yeah, the problem is that I'm pretty sure some stuff is broken, but I'm not sure what, and I can't test/fix it, because I think I'm banned for the next 6 hours or so.

Everything is working in the pigskin repo, so the core functionality should all work.

Can someone pull the latest code from this repo, test it, and take a whack at fixing any problems that crop up? I'm hoping to get this addon functional again before Sunday's games...

[1] We should take a look at this. Whether we need to be cleaning up with a logout() function, or better detecting if we're already logged in and skip the login process if we already have access (which is what I'm leaning towards).

**Comment by tinzarian** [comment]
I tried a couple of games, NFL Networl live and some shows and it all seemed to work fine.

**Comment by aqw** [comment]
@tinzarian Really!? That's wonderful. I must have been very lucky, and the last bug I fixed was the last bug.

Thanks for testing this!
