### ISSUE TITLE
Can't reload gamelist

### ISSUE THREAD

**Issue by tinzarian** [aqw/xbmc-gamepass#401]
I'm not sure i this is related to any other already reported issue, apologies if it is, 
How to recreate: 
- Open the addon, click on the Gamepass button at the top. The list of the current week's games is loaded.
- Exit the addon, reopen it and click on the Gamepass button again, the list of games will not load. When trying to load  week one on the left hand side an error pops up. The preseason-weeks seem to work ok
- After a restart of kodi the page is correctly loaded (until you exit)

Log is here: http://ix.io/1moY

**Comment by OnceUponALoop** [comment]
It seems the log doesn't have debugging enabled - can you resubmit with DEBUG on. 

You can do that in the GUI menu or in advancedsettings.xml if you want to hide on-screen debug info
``` xml
<advancedsettings>
    <loglevel>2</loglevel>
</advancedsettings>
```

**Comment by tinzarian** [comment]
Debug logging is on. That's why all those line with debug info are there.

**Comment by tinzarian** [comment]
I added the setting, but... it may have been a serverside issue, since it works as expected at the moment, and I can't recreate the error.
I'll close this issue.
