### ISSUE TITLE
Kodi Leia problem

### ISSUE THREAD

**Issue by MiranDalic** [aqw/xbmc-gamepass#421]
My SONY TV install automatically Leia over Kripton and I got message that GP is not compatible with Leia. Could be fixed somehow or I have manually install Krypton ?

**Comment by aqw** [comment]
Closing as it is a duplicate of #373 

This addon will be updated before the 2019 season starts, but as I am currently changing jobs and moving, it won't be anytime in the immediate future.

---Alex
