### ISSUE TITLE
Video doesn't start.

### ISSUE THREAD

**Issue by Tuhwin** [aqw/xbmc-gamepass#424]
The 2019/2020 season starting soon so I wanted to make sure everything was working.
Tried playing a few videos - Top100 from NFL Network/2019 - but none of them start.
Enabled debugging and closed down everything, started it up to get fresh logs and immediately went to Gamepass and tested said videos. Nothing happened so I went into settings and enabled AdaptiveInput and tried again, with no success.

Logs included.
Is it on my end or is there changes to the service since last season that require you guys to update the addon?
[kodi.log](https://github.com/aqw/xbmc-gamepass/files/3431514/kodi.log)

**Comment by Tuhwin** [comment]
Am I alone in this? The lack of responses from devs or others finding themselves having the same issue seems to suggest this.

**Comment by jm-duke** [comment]
I tried a few minutes ago and I was able to play some 2019 Top 100 Streams. The recent HoF game was working as well.

Do you use the addon version installed from the Kodi repos, or the current master?

Cheers,
Tom.

**Comment by Tuhwin** [comment]
Thanks for testing and chiming in on this, much appreciated.
I tested with the master from here on github. I wasn't aware that there's a version available elsewhere. Seems like I've missed out on something, or not researched it enough then.

Will look in the repos and see there. Maybe it's because I still use Kodi 17, 18 works horribly on my htpc and I can't for the love of me get it to work, either by upgrading or fresh installing. Audio/video issues in all forms.

But thanks, will look into this.

**Comment by Tuhwin** [comment]
Found it on the Kodi repo, so thanks for that.
However I did encounter login errors suddenly which is preventing me from testing if streaming is working or not, so I'll close this issue as resolved as it works for you and I can not verify that it isn't for me, and then combat the login issues instead.
