### ISSUE TITLE
Alternate Team Audio

### ISSUE THREAD

**Issue by aqw** [aqw/xbmc-gamepass#86]
Team audio is usually posted a day or two after the game, and is usually of the local radio networks for a team. As such, the commentary tends to be much more insightful than the nationwide TV anchors.

The downside of the flash interface is that the audio tends to be out of sync by a few seconds (due to TV vs Radio delay). XBMC makes it easy to adjust the timing of streams, so adding this feature to XBMC could actually make it bearable to watch games with team audio.

**Comment by kaileu** [comment]
The available audio streams are delivered through the m3u8 file.
example colts vs bengals:
http://pastebin.com/uCL00YRg

**Comment by kaileu** [comment]
Is there a function  to add a 2nd Audio Stream to the Video stream i looked into the Kodi API but didn't find a suitable function which takes Stream as Input

**Comment by Alexqw** [comment]
@kaileu I think the way to do this is add the audio stream info to the m3u8 that we're passing to kodi. Then kodi will handle it.

What I'm unsure about is how Kodi/ffmpeg will respond to passing along a custom m3u8 file.

---Alex

**Comment by aqw** [comment]
Closing, as alternate team audio is no longer provided. :-/

---Alex
